import { Metadata } from '@webpackages/types';

export const SerialNumberMetadata: Metadata = {
  groupName: 'administation',
  properties: {
    serialNumber: {
      type: 'string',
      required: true,
      minimum: 5,
      example: '1236846182674312',
      description: 'Unique product serial number to track product',
    },
    inStock: {
      type: 'boolean',
      required: true,
      example: true,
      description:
        'When the product is sold, uncheckk this property (internal)',
    },
    generated: {
      type: 'boolean',
      description: `if the serial number is generated by the system check this property (internal)`,
      example: false,
    },
  },
  relations: {
    sku: {
      relationType: 'owner',
      targetName: 'Sku',
      viewColumns: ['sku', 'name'],
      resourceLabelProperty: 'name',
    },
  },
};
