import { Metadata } from '@webpackages/types';

export const SerialNumberMetadata: Metadata = {
  groupName: 'administation',
  properties: {
    serialNumber: {
      type: 'string',
      required: true,
      minLength: 3,
      maxLength: 100,
      example: '1236846182674312',
      description: 'Unique product serial number to track product',
      class: 'order-2 w-4/12 grow',
      tabIndex: 2,
    },
    inStock: {
      type: 'boolean',
      label: 'In Stock',
      inputType: 'checkbox',
      example: true,
      description:
        'When the product is sold, uncheckk this property (internal)',
      class: 'order-3 w-full ',
      tabIndex: 3,

      tableColumnClass: 'w-16',
      tableColumnConditionalClass(value: any) {
        return value.inStock == true ? 'bg-green-400' : 'bg-red-400';
      },

      map(value) {
        return value.inStock === true ? 'YES' : 'NO';
      },
    },
    generated: {
      type: 'boolean',
      inputType: 'checkbox',
      description: `if the serial number is generated by the system check this property (internal)`,
      example: false,
      class: 'order-4 w-full ',
      tabIndex: 4,
    },
  },
  relations: {
    sku: {
      relationType: 'owner',
      targetName: 'Sku',
      label: '',
      viewColumns: ['sku', 'name'],
      resourceLabelProperty: 'name',
      update: false,
      class: 'order-1 w-4/12 grow',
      tabIndex: 1,
    },
  },
};
