module.exports = {
  apps: [
    {
      name: 'api-prod',
      script: 'dist/apps/api/main.js',
      autorestart: true,
      watch: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        APP_NAME: 'Api-Production',
        APP_DESCRIPTION: 'Product environment',
        PORT: 3005,
        ROOT_USERNAME: 'root',
        ROOT_PASSWORD: 'password',
        DATABASE: 'bms',
        DATABASE_USERNAME: 'appuser',
        DATABASE_PASSWORD: 'appuser',
        JWT_SECRET: 'Super Secret',
        LOG_LEVEL: 'fatal,error',
      },
    },
    // For testing purpose
    {
      name: 'api-dev',
      script: 'dist/apps/api/main.js',
      autorestart: true,
      watch: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        APP_NAME: 'Api-Dev',
        APP_DESCRIPTION: 'Development environment',
        PORT: 3000,
        ROOT_USERNAME: 'root',
        ROOT_PASSWORD: 'password',
        JWT_SECRET: 'Super Secret',
        DATABASE: 'devdb',
        DATABASE_USERNAME: 'devuser',
        DATABASE_PASSWORD: 'devuser',
        LOG_LEVEL: 'debug,fatal,error,warn',
      },
    },
    {
      name: 'api-no-security',
      script: 'dist/apps/api/main.js',
      autorestart: true,
      watch: true,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        APP_NAME: 'Api-No-Security',
        APP_DESCRIPTION: 'No-Security environment',
        PORT: 3001,
        BYPASS_SECURITY: true,
        ROOT_USERNAME: 'root',
        ROOT_PASSWORD: 'password',
        JWT_SECRET: 'Super Secret',
        DATABASE: 'devdb',
        DATABASE_USERNAME: 'devuser',
        DATABASE_PASSWORD: 'devuser',
        LOG_LEVEL: 'debug,fatal,error,warn',
        BYPASS_AUTH_GUARD: true,
      },
    },
  ],
};
