import { IDDto } from '@webpackages/database';
import { Property } from '@webpackages/property';
import { Exclude } from 'class-transformer';

@Exclude()
export class CreateSerialNumberDto {
  @Property({
    type: 'string',
    required: true,
    minLength: 3,
    maxLength: 100,
    example: '1236846182674312',
    description: 'Unique product serial number to track product',
  })
  serialNumber: string;
  @Property({
    type: 'boolean',
    inputType: 'checkbox',
    example: true,
    description: 'When the product is sold, uncheckk this property (internal)',
  })
  inStock: boolean;
  @Property({
    type: 'boolean',
    inputType: 'checkbox',
    description:
      'if the serial number is generated by the system check this property (internal)',
    example: false,
  })
  generated: boolean;

  @Property({ type: 'number', required: true })
  sku: IDDto;
}
