import { Exclude } from 'class-transformer';
import { Property } from '@webpackages/property';
import { IDDto } from '@webpackages/database';

@Exclude()
export class UpdateSerialNumberDto {
  @Property({
    type: 'string',
    minLength: 3,
    maxLength: 100,
    example: '1236846182674312',
    description: 'Unique product serial number to track product',
  })
  serialNumber: string;
  @Property({
    type: 'boolean',
    inputType: 'checkbox',
    example: true,
    description: 'When the product is sold, uncheckk this property (internal)',
  })
  inStock: boolean;
  @Property({
    type: 'boolean',
    inputType: 'checkbox',
    description:
      'if the serial number is generated by the system check this property (internal)',
    example: false,
  })
  generated: boolean;
}
