import { Exclude } from 'class-transformer';
import { Property } from '@webpackages/property';
import { IDDto } from '@webpackages/database';

@Exclude()
export class UpdateSerialNumberDto {
  @Property({
    type: 'string',
    unique: true,
    minLength: 3,
    maxLength: 100,
    example: '1236846182674312',
    description: 'Unique product serial number to track product',
    class: 'order-2 w-4/12 grow',
    tabIndex: 2,
  })
  serialNumber: string;
  @Property({
    type: 'boolean',
    label: 'In Stock',
    inputType: 'checkbox',
    example: true,
    description: 'When the product is sold, uncheckk this property (internal)',
    class: 'order-3 w-full ',
    tabIndex: 3,
    tableColumnClass: 'w-16',
  })
  inStock: boolean;
  @Property({
    type: 'boolean',
    inputType: 'checkbox',
    description:
      'if the serial number is generated by the system check this property (internal)',
    example: false,
    class: 'order-4 w-full ',
    tabIndex: 4,
  })
  generated: boolean;
}
