// @index('./**/*.component.ts', f => `export * from '${f.path}'`)
export * from './lib/autocomplete-many/autocomplete-many.component'
export * from './lib/autocomplete/autocomplete.component'
export * from './lib/button-toggle/button-toggle.component'
export * from './lib/input-date/input-date.component'
export * from './lib/input-number/input-number.component'
export * from './lib/input-text/input-text.component'
export * from './lib/input-textarea/input-textarea.component'
export * from './lib/input/input.component'
export * from './lib/search-many/search-many.component'
export * from './lib/search/search.component'
export * from './lib/select/select.component'
export * from './lib/slider-toggle/slider-toggle.component'
